# Generated by Django 5.1.1 on 2024-09-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='title',
            new_name='name',
        ),
    ]
