# Generated by Django 5.1.1 on 2024-09-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_title_cake_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='user',
        ),
    ]
