# Generated by Django 5.1.1 on 2024-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_cake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/'),
        ),
    ]
