# Generated by Django 5.1.1 on 2024-09-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='falovor',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
